### ISSUE TITLE
blueprint navigation

### ISSUE THREAD

**Issue by jalex-stark** [leanprover-community/sphere-eversion#5]
Add a link that goes from 
https://leanprover-community.github.io/sphere-eversion/blueprint/index.html
to
https://leanprover-community.github.io/sphere-eversion/

https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Sphere.20eversion.20project/near/199718684

**Comment by jcommelin** [comment]
In general, I think there is no link to the homepage from any of the subpages of the blueprint (e.g. the interactive graph).

**Comment by jalex-stark** [comment]
> In general, I think there is no link to the homepage from any of the subpages of the blueprint (e.g. the interactive graph).

Yeah, I think the link should go into the big blue navigation sidebar. I don't know enough about how it works to make a more concrete suggestion.

**Comment by PatrickMassot** [comment]
I think this all fixed now.
